import dimensions from "@/lib/generated/image-dimensions.json";

export interface ImageDimensions {
  width: number;
  height: number;
}

const map: Record<string, ImageDimensions> = dimensions;

/**
 * Real pixel dimensions for an image under /public/images, generated by
 * scripts/build-image-dimensions.mjs. Used to size a swatch's container to
 * its exact native aspect ratio instead of forcing a fixed box.
 */
export function getImageDimensions(src: string): ImageDimensions | null {
  return map[src] ?? null;
}
